# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "Example"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

engines:
  template:
    template_toolkit:
      # Note: start_tag and end_tag are regexes
      start_tag: '[%'
      end_tag:   '%]'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.

session: YAML

engines:
  session:
    YAML:
      cookie_name: testapp.session

# database configuration
database:
  dsn: "dbi:SQLite:dbname=Example/db/example.db"
  username: ""
  password: ""

# Google OAuth2 configuration
oauth:
  google:
    client_id: "YOUR_GOOGLE_CLIENT_ID"
    client_secret: "YOUR_GOOGLE_CLIENT_SECRET"
    redirect_uri: "http://localhost:3000/auth/google/callback"
    scope: "email profile"

# To get the Google client id and Google client secret values, follow these steps:
# 1. Go to the Google Cloud Console: https://console.cloud.google.com/
# 2. Create a new project or select an existing project.
# 3. Navigate to the "Credentials" page from the left-hand menu.
# 4. Click on "Create credentials" and select "OAuth 2.0 Client IDs".
# 5. Configure the OAuth consent screen if you haven't already.
# 6. Fill in the required information and set the redirect URI to "http://localhost:3000/auth/google/callback".
# 7. After creating the credentials, you will see the client ID and client secret values.
